= floatimage

This is image implementations based on float64 and float32 values for image channels RGBA.

Images are RGB with alpha or premultiplied alpha channels. All channels are 64 or 32 bit float values. Expected value range for each channel is [0.0, 1.0]. Nothing stops the channel values to be outside the valid value interval but any call to the Color interface function `RGBA() (r, g, b, a uint32)` will clamp the values to the valid range.

All image formats are backed by an accompanying color model.

* NRGBAF64 - Color and RGB image with _ordinary alpha_ (non premultiplied). All channels are encoded as a 64 bit float value (per pixel).
* NRGBAF32 - Color and RGB image with _ordinary alpha_ (non premultiplied). All channels are encoded as a 32 bit float value (per pixel).
* RGBAF64 - Color and RGB image with _premultiplied alpha_. All channels are encoded as a 64 bit float value (per pixel).
* RGBAF32 - Color and RGB image with _premultiplied alpha_. All channels are encoded as a 32 bit float value (per pixel).
